apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "cinemify-mysql.cfeyyyka4nms.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "cinemify"
  DB_USER: "cinemifyadmin"
  PORT: "5000"
  NODE_ENV: "production"
  CORS_ORIGIN: "https://cinemify.in"
  ACCESS_TOKEN_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN_DAYS: "30"
  AWS_REGION: "ap-south-1"
